### ISSUE TITLE
json-ld examples for linked entities clarification required

### ISSUE THREAD

**Issue by rduyme** [skg-if/context#4]
Following discussion about "json-ld examples as specs" today.

We have : 
-https://github.com/skg-if/context/blob/main/ver/1.0.1/samples/example-research-product.json (covering all fields, linked entity ids )
- https://github.com/skg-if/examples/blob/main/OpenCitations/oc_1.jsonld (Silvio, not covering all fields, linked entities embedded)
- https://zenodo.org/records/13318745 ( v1.1 linked entity ids ). OpenAire examples 

Which is official one ?
- One return full person entity embedded (Silvio), the other only person id.
- One as links to reference publications id, the other one no reference (Silvio's one, impossible to know if it is by convention or missing data)

Do we consider both valid, and leave choice to client to execute additional calls to get "missing" information (1 call for each person, 1 call for each topic ) ? or is embedded the recommended approach ?
 
This also raises issue on approach for "otf" ids. (incompatible with additional call) 

As part of OSTrails, we tried to define clear conventions for each end point (see get single by id end points/ similar to skg-if resolve)  : https://gitlab.esrf.fr/smis/ostrails/-/tree/main/skg-if-api .  
We chose to embed entities ( like done by Silvio). 
I think all the fields are covered, especially on linked embedded entities, where clear guidance is required for future implementers (ex: product embed the grant but not grant.beneficiaries).

I understand these json-ld conventions for single entity end point (by example or by documentation) are **not** part of the extension. Meaning SKG-IF github must take responsibility for "get by id"/"resolve by id" documentation.

(and we leave search api outside of the SKG-IF for now )

**Comment by essepuntato** [comment]
Both the cases you describe are valid, and it is up to the data provider to decide if it wants to explain fully all the entities introduced or reference them, leaving the user to ask for additional information if needed. From an SKG-IF point of view, we cannot be prescriptive here and oblige a provider to follow one path or the other. Thus, in the example of OSTRails, it is totally fine if you define your own convention, being compliant with SKG-IF of course.

**Comment by rduyme** [comment]
Ok thanks Silvio for clarification. you draw the line of responsibility. it's very useful.

Why not adding this, to the documentation  :

- Json-ld examples are json-ld compatible with @context provided
- An SKG-IF data provider may have to define conventions on what resolve API endpoint will exactly return for each entity. (how linked entities are included : linked vs embedded, mandatory fields to include ? )
